---
title: "flight_data_web_scrape"
output: md_document
date: "2026-02-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Scraping Capacity Numbers from Wikipedia

```{r}
library(tidyverse)
library(rvest)

# This Wikipedia page has 31 US Large Hub Airports and capacity numbers from 2015-2024
page <- read_html("https://en.wikipedia.org/wiki/List_of_the_busiest_airports_in_the_United_States")

capacity <- page %>% html_element(xpath='//*[@id="mw-content-text"]/div[2]/table[1]') %>% html_table()
colnames(capacity) <- c("Rank","Name","Airport","Cities","Metro Area","State","2024","2023","2022","2021","2020","2019","2018","2017","2016","2015")

# Select only IATA Code and The Capacity Numbers by Year
capacity <- capacity[,c(3,7:16)] %>% as.data.frame()
capacity %>% head()
```


# Bring in Flight Delay Data from 2015 to 2024

```{r}
delay <- read.csv("delay_core_2015_2024.csv")
delay <- delay %>% filter(Year%in%c("2015","2016","2017","2018","2019","2020","2021","2022","2023","2024"))
```

```{r}
top10 <- delay %>% group_by(Loc) %>%
  summarise(Total.Delays=sum(Tot.Delays)) %>%
  arrange(desc(Total.Delays))
top10$Loc[1:10]
top10
```

Top 10 Airports with the Most Total Delays from 2015-2024:

1. LGA (NY)
2. EWR (NJ)
3. SFO (CA)
4. ORD (IL)
5. JFK (NY)
6. LAX (CA)
7. LAS (NV)
8. DFW (TX)
9. BOS (MA)
10. PHL (PA)


```{r}
onlytop5 <- delay %>% filter(Loc %in% top10$Loc[c(1:5)])
ggplot(onlytop5,aes(x=Year,y=Tot.Delays,color=Loc,group=Loc)) + 
  geom_point() +
  geom_line() +
  labs(title="Total Flight Delays of Top 5 Airports with Most Delayed Operations",
       y = "Annual Delayed Operations",
       color = "Airport")
```

